language: java
jdk: oraclejdk9
dist: trusty
addons:
  sonarcloud:
    organization: "saschawiegleb"
    token:
      secure: "$SONAR_TOKEN"
before_script:
  - chmod +x gradlew
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
